### ISSUE TITLE
(2019-06-25) 리액트, 타입스크립트 시작하기 포스트 중 오타

### ISSUE THREAD

**Issue by 0xBono** [jeonghwan-kim/jeonghwan-kim.github.com#159]
`npm install --save-dev ts-loader webpack weboack-cli`
다음과 같은 부분에서 weboack-cli => webpack-cli로 변경하면 좋을 거 같습니다.  

<img width="739" alt="스크린샷 2020-07-29 오후 6 51 34" src="https://user-images.githubusercontent.com/59228569/88785730-8732ac00-d1cc-11ea-9e26-33821c74a23f.png">

**Comment by jeonghwan-kim** [comment]
@0xBono 오타 제보 해주신 이슈를 너무 늦게 확인했네요. 고맙습니다. :D
