### ISSUE TITLE
Angular Facts Easy to Miss 라는 글에서 인터폴레이션 문자열이 블로그에서 렌더링 되지 않는 문제가 있습니다.

### ISSUE THREAD

**Issue by minhoryang** [jeonghwan-kim/jeonghwan-kim.github.com#29]
Angular Facts Easy to Miss 라는 글에서 인터폴레이션 문자열이 블로그에서 렌더링 되지 않는 문제가 있습니다.

Where:
- [L21](https://github.com/jeonghwan-kim/jeonghwan-kim.github.com/blame/master/_posts/2016/2016-08-20-angular-facts-easy-to-miss.md#L21)
- [L33-L34](https://github.com/jeonghwan-kim/jeonghwan-kim.github.com/blame/master/_posts/2016/2016-08-20-angular-facts-easy-to-miss.md#L33-L34)

Expected: `{{name}}`이 보였으면 합니다.

Happened: 그 자리에 아무것도 보이지 않습니다. 템플릿 엔진이 소화한 것 아닐까?싶습니다.

좋은글 감사합니다!

**Comment by jeonghwan-kim** [comment]
오타 교정까지해주시다니 고맙습니다.^^ 템플릿 엔진이 해석해서 안나온것 같습니다.
